title: 'The Contact Sheet '
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.4032258
  brandStrength: 0.4892473
  rhythmicContrast: 0.7132617
  brandColors:
    - '#45617E'
    - '#B0B2B4'
    - '#DBD8D3'
    - '#303030'
    - '#788188'
  lightness: 0.6935484
navigation:
  - name: About
    id: 7cde3189-f37a-4846-9b50-bafb27c83bdb
    type: content
cta:
  bucket: null
  version: null
  domain: null
favicon: null
analytics:
  twitter: null
  google: null
  facebook: null
name: Michael Swamer Photo
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.2809782933909446
layout_spectrum: 0.2706093
