name: High Line Media
favicon: null
layout_spectrum: 0.21572701819241047
typography_spectrum: 0.32805698039010167
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.7775201832409948
  lightness: 0.6243412769399583
  saturation: 0.8588079011533409
  rhythmicContrast: 0.2485987045802176
purpose: []
