layout_spectrum: 0.6846526728477329
typography_spectrum: 0.2809782933909446
color:
  saturation: 0.4032258
  brandStrength: 0.4892473
  lightness: 0.6935484
  brandColors:
    - '#45617E'
    - '#B0B2B4'
    - '#DBD8D3'
    - '#303030'
    - '#788188'
  rhythmicContrast: 0.7132617
title: 'The Contact Sheet '
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
name: Michael Swamer Photo
favicon: null
opengraph:
  image: null
  type: null
  appId: null
